<a href="https://colab.research.google.com/github/Imene-Ezzeddine/ExData_Plotting1/blob/master/streamlit_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:

pip install streamlit==1.13.0


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


1. Import the necessary libraries: Streamlit, sklearn.datasets, and sklearn.ensemble.

In [51]:
import pandas as pd
import streamlit as st
from sklearn import datasets
from sklearn import ensemble


2. Load the iris dataset using the "datasets.load_iris()" function and assign the data and target variables to "X" and "Y", respectively.

In [52]:
iris = datasets.load_iris()
# Creating a DataFrame of given iris dataset.
import pandas as pd
data=pd.DataFrame({
    'sepal length':iris.data[:,0],
    'sepal width':iris.data[:,1],
    'petal length':iris.data[:,2],
    'petal width':iris.data[:,3],
    'species':iris.target
})
species = []
for i in range(len(data['species'])):
    if data['species'][i] == 0:
        species.append("setosa")
    elif data['species'][i] == 1:
        species.append('versicolor')
    else:
        species.append('virginica')
data['species'] = species

data.head()
X=data[['sepal length', 'sepal width', 'petal length', 'petal width']]
y=data['species']
print(data)


     sepal length  sepal width  petal length  petal width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


3. Set up a Random Forest Classifier and fit the model using the "RandomForestClassifier()" and "fit()" functions.

In [53]:
#Data training
from sklearn.model_selection import train_test_split
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
#Fit data using Random Forest Model
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
# Confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))


[[17  0  0]
 [ 0 15  0]
 [ 0  1 12]]


4. Create a Streamlit app using the "streamlit.title()" and "streamlit.header()" functions to add a title and header to the app.
5. Add input fields for sepal length, sepal width, petal length, and petal width using the "streamlit.slider()" function. Use the minimum, maximum, and mean values of each feature as the arguments for the function.
6. Define a prediction button using the "streamlit.button()" function that takes in the input values and uses the classifier to predict the type of iris flower
7. Use the "streamlit.write()" function to display the predicted type of iris flower on the app.


In [54]:
! pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [58]:
%%writefile app.py
import numpy as np
import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier

st.write(''' # Simple Iris Flower Prediction App''')
st.sidebar.header('User Input Parameters')
def user_input_features():
  sepal_length = st.sidebar.slider('sepal length', 4.3, 7.9, 5.4)
  sepal_width = st.sidebar.slider('sepal width', 2.0, 4.4, 3.4)
  petal_length = st.sidebar.slider('petal length', 1.0, 6.9, 1.3)
  petal_width = st.sidebar.slider('petal width', 0.1, 2.5, 0.2)

  user_input_data = {'sepal_length': sepal_length,
               ' sepal_width': sepal_width,
               'petal_length': petal_length,
               'petal_width': petal_width}

  features = pd.DataFrame(user_input_data, index=[0])
  return features
df = user_input_features()
st.subheader('User Input Parameters')
st.write(df)

iris = datasets.load_iris()
X = iris.data
Y = iris.target

classifier = RandomForestClassifier()
classifier.fit(X, Y)

pred = classifier.predict(df)
if pred == 0:
  prediction = "setosa"
elif pred == 1:
  prediction = "versicolor"
elif pred == 2:
  prediction = "virginica"
classify = st.button('Classify')
if classify:
  st.subheader("The flower type is:")
  st.write(prediction)

Overwriting app.py


In [59]:
!streamlit run /content/app.py & npx localtunnel --port 8501

2023-03-23 12:08:44.149 INFO    numexpr.utils: NumExpr defaulting to 2 threads.
npx: installed 22 in 3.497s
your url is: https://silver-bugs-nail-34-125-50-192.loca.lt



  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.12:8501
  External URL: http://34.125.50.192:8501

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/lo